export const environment = {
production: true,
SUPABASE_URL: 'https://ycnbwomrhfvgmgavglwc.supabase.co',
SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljbmJ3b21yaGZ2Z21nYXZnbHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAxMjg5MjcsImV4cCI6MjA0NTcwNDkyN30.5qKlILqFNV7SX_O6SRx31LMUSjVPHpbmvxcCB26uCa0'

};
